// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoR02CNWIMIFDj9UmAKmB4SPFY7gTc1fg',
    appId: '1:418138450220:web:6e8aaa66f30825f9642489',
    messagingSenderId: '418138450220',
    projectId: 'myperfectpg-f6a53',
    authDomain: 'myperfectpg-f6a53.firebaseapp.com',
    storageBucket: 'myperfectpg-f6a53.appspot.com',
    measurementId: 'G-J35F8M9DSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8d6KhvmUCIV_T6VI748rSPvK1WeGvMI',
    appId: '1:418138450220:android:24010fe38971ea7b642489',
    messagingSenderId: '418138450220',
    projectId: 'myperfectpg-f6a53',
    storageBucket: 'myperfectpg-f6a53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5A0sZtIIJlEdvUK9r49eACIAx-qRM78',
    appId: '1:418138450220:ios:00cdbc0f86dbbb3d642489',
    messagingSenderId: '418138450220',
    projectId: 'myperfectpg-f6a53',
    storageBucket: 'myperfectpg-f6a53.appspot.com',
    iosBundleId: 'com.example.ownerMyperfectPg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5A0sZtIIJlEdvUK9r49eACIAx-qRM78',
    appId: '1:418138450220:ios:00cdbc0f86dbbb3d642489',
    messagingSenderId: '418138450220',
    projectId: 'myperfectpg-f6a53',
    storageBucket: 'myperfectpg-f6a53.appspot.com',
    iosBundleId: 'com.example.ownerMyperfectPg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoR02CNWIMIFDj9UmAKmB4SPFY7gTc1fg',
    appId: '1:418138450220:web:ffdf8b6957135a99642489',
    messagingSenderId: '418138450220',
    projectId: 'myperfectpg-f6a53',
    authDomain: 'myperfectpg-f6a53.firebaseapp.com',
    storageBucket: 'myperfectpg-f6a53.appspot.com',
    measurementId: 'G-MTN1FYP0RQ',
  );
}
